### ISSUE TITLE
Add helper method to Transport for adding outbound handlers

### ISSUE THREAD

**Issue by justinvdm** [praekelt/vumi-ureport#33]
`Transport` has an internal method `_process_message`, which wraps `handle_outbound_message`. We need to make it possible for extra outbound handlers to be added for different endpoints, and have it wrapped in something simlar to `_process_message`.

**Comment by hodgestar** [comment]
Is this ticket in the right repository?

**Comment by justinvdm** [comment]
Woops, thanks :) Closing.
